### ISSUE TITLE
Plugin load error

### ISSUE THREAD

**Issue by joaorsb** [alaxos/cakephp3-libs#2]
Cake (Im on cake version 3.1.4) plugin installer is generating the config file cakephp-plugins.php pointing to 'Alaxos' => $baseDir . '/vendor/alaxos/cakephp3-libs/', instead of  '/vendor/alaxos/Alaxos'.  Total noob here, so I dont really know how to fix it.

**Comment by alaxos** [comment]
Just done a fresh insall of Cake + cakephp3-libs via composer and its seems to work. Did you use composer to make your install ?

**Comment by joaorsb** [comment]
Thank you for the answer, and yes I'm using composer. Will try again and dig more to see if I can find the problem.
